import { atom } from "recoil";

const studyListState = atom({
  key: `studyList`,
  default: [
    {
      category: "etc",
      members: 1,
      title: "UX 디자인 실습하기",
      author: "김민태",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "debate",
      members: 5,
      title: "달리기 수업",
      author: "이성용",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "debate",
      members: 1,
      title: "달리기 수업",
      author: "이성용",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "announcement",
      members: 1,
      title: "드론과 현장 : 산림 편",
      author: "최용호",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "debate",
      members: 4,
      title: "UX 디자인 실습하기",
      author: "이경주",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "debate",
      members: 4,
      title: "UX 디자인 실습하기",
      author: "이유진",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "debate",
      members: 3,
      title: "UX 디자인 실습하기",
      author: "김준홍",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "portfolio",
      members: 2,
      title: "달리기 수업",
      author: "이경주",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "portfolio",
      members: 2,
      title: "달리기 수업",
      author: "지주연",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "debate",
      members: 5,
      title: "노자 도덕경",
      author: "이성용",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "writing",
      members: 3,
      title: "오래자기 챌린지",
      author: "손주리",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "announcement",
      members: 2,
      title: "코로나 팬데믹 리포트",
      author: "이성용",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "debate",
      members: 1,
      title: "드론과 현장 : 산림 편",
      author: "손주리",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "announcement",
      members: 1,
      title: "UX 디자인 실습하기",
      author: "이성용",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "writing",
      members: 5,
      title: "드론과 현장 : 산림 편",
      author: "김민태",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "debate",
      members: 4,
      title: "노자 도덕경",
      author: "이유진",
      date: "04.26 ~ 05.26 토 14:00",
    },
    {
      category: "debate",
      members: 4,
      title: "노자 도덕경",
      author: "유상원",
      date: "04.26 ~ 05.26 토 14:00",
    },
  ],
});

export { studyListState };
